apiVersion: v1
data:
  config.yaml: |
    server:
      http1:
        name: httpserver1
        addr: 0.0.0.0:8081
      http2:
        name: httpserver2
        addr: 0.0.0.0:8082
kind: ConfigMap
metadata:
  name: httpserver-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cncamp-httpserver
  name: cncamp-httpserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cncamp-httpserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: cncamp-httpserver
    spec:
      containers:
        - image: huangzhihong/cncamp:httpserver-v3
          name: httpserver
          resources:
            requests:
              memory: 64Mi
              cpu: 250m
            limits:
              memory: 128Mi
              cpu: 500m
          volumeMounts:
            - name: config
              mountPath: "/app/configs/"
              readOnly: true
#          lifecycle:
#            postStart:
#              exec:
#                command:
#                  - /bin/sh
#                  - -c
#                  - sleep 60
          livenessProbe:
            httpGet:
              path: /livenesshealthz
              port: 8081
            initialDelaySeconds: 60
            failureThreshold: 1
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readinesshealthz
              port: 8081
            periodSeconds: 5
            successThreshold: 2
          startupProbe:
            httpGet:
              path: /startuphealthz
              port: 8081
            failureThreshold: 30
            periodSeconds: 10
            
      volumes:
        - name: config
          configMap:
            name: httpserver-config
            items:
              - key: "config.yaml"
                path: "config.yaml"
